### ISSUE TITLE
New test configuration example

### ISSUE THREAD

**Issue by goors** [loadimpact/loadimpact-sdk-python#4]
Your new test configuration example is not working: https://github.com/loadimpact/loadimpact-sdk-python#create-a-new-test-configuration.

I am getting: 

<pre>
File "assignment.py", line 122, in <module>
    load.createTestConfiguration()
  File "assignment.py", line 104, in createTestConfiguration
    "loadzone": LoadZone.RACKSPACE_UK_LONDON
  File "/Library/Python/2.7/site-packages/loadimpact/clients.py", line 104, in create_test_config
    return TestConfig.create(self, data)
  File "/Library/Python/2.7/site-packages/loadimpact/resources.py", line 111, in create
    file_object=file_object)
  File "/Library/Python/2.7/site-packages/loadimpact/clients.py", line 51, in wrapper
    return func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/loadimpact/clients.py", line 193, in post
    return self._check_response(response)
  File "/Library/Python/2.7/site-packages/loadimpact/clients.py", line 235, in _check_response
    raise ClientError(msg, response=response)
loadimpact.exceptions.ClientError: Validation failed (https://api.loadimpact.com/v2/test-configs)
</pre>

I suspected that is not working because of subscription. 
So i try to put duraion 60 and duration 1 since it is not clear what is duration on your api minutes or seconds?

How can I check why validation is failing?

**Comment by eLobeto** [comment]
This issue is happening to me as well. It would be great to have some light shed on this.

**Comment by robingustafsson** [comment]
My apologies for this very late response on original report of this issue @goors, and thanks for reporting this again @eLobeto. I'll have a look and see how we can improve the error message returned from the API. Totally agree it's not helpful as it is now.

I'll also update our [v2 API docs](http://developers.loadimpact.com/api/index.html) and Python SDK README to clarify the unit for "duration" which is supposed to be specified in minutes.

**Comment by robingustafsson** [comment]
@eLobeto Would you mind sharing the test config you were trying to create with the SDK when you got the "Validation failed" error?

**Comment by eLobeto** [comment]
Sure, thanks for looking into it!
I've been trying to use:
```
config = client.create_test_config({
    'name': 'Default Test',
    'url': 'http://www.google.com/',
    'config': {
        "user_type": "sbu",
        "load_schedule": [{"users": 50, "duration": 5}],
        "tracks": [{
            "clips": [{
                "user_scenario_id": 1, "percent": 100
            }],
            "loadzone": LoadZone.AMAZON_US_ASHBURN
        }]
    }
})
```

**Comment by robingustafsson** [comment]
Thanks. I've now improved the API error handling in the SDK to print the error message present in the response from the API (initially I thought the API didn't return any useful error, but it actually does since 6 months back).

I've uploaded a new version of the SDK to PyPI, [v1.1.3](https://pypi.python.org/pypi/loadimpact/1.1.3).

The error in your case is that the user scenario (with ID 1) referenced in the config is not from your account. Here is an extended version of your example that includes the creation of a user scenario:

```python
import loadimpact

# Setup API client
client = loadimpact.ApiTokenClient(api_token='...')

# Create user scenario
load_script = """
local response = http.get("http://www.google.com')
log.info("Load time: "..response.total_load_time.."s")
client.sleep(10)
"""
user_scenario = client.create_user_scenario({
    'name': "My user scenario",
    'load_script': load_script
})

# Create test config with user scenario created above
config = client.create_test_config({
    'name': 'Default Test',
    'url': 'http://www.google.com/',
    'config': {
        "user_type": "sbu",
        "load_schedule": [{"users": 50, "duration": 5}],
        "tracks": [{
            "clips": [{
                "user_scenario_id": user_scenario.id, "percent": 100
            }],
            "loadzone": loadimpact.LoadZone.AMAZON_US_ASHBURN
        }]
    }
})
```

Thanks again for reporting. Closing this issue.
