### ISSUE TITLE
create_data_store failing

### ISSUE THREAD

**Issue by timwintle** [loadimpact/loadimpact-sdk-python#5]
Python 2.7:

My code:

  client.create_data_store({
				'name': datastore_name,
				'separator': 'comma',
				'delimeter': 'double',
				'fromline': 0
			}, StringIO("test,test,test"))

Output (auth snipped):

send: 'POST /v2/data-stores HTTP/1.1\r\nHost: api.loadimpact.com\r\nContent-Length: 528\r\nAccept-Encoding: gzip, deflate\r\nAccept: */*\r\nuser-agent: LoadImpactPythonSDK/1.1.3 (python 2.7.6; requests 2.7.0)\r\nConnection: keep-alive\r\nContent-Type: multipart/form-data; boundary=9d85bfe775eb4da6a4b39643d9b62963\r\nAuthorization: Basic {PRIVATE AUTH DATA}=\r\n\r\n--9d85bfe775eb4da6a4b39643d9b62963\r\nContent-Disposition: form-data; name="fromline"\r\n\r\n0\r\n--9d85bfe775eb4da6a4b39643d9b62963\r\nContent-Disposition: form-data; name="separator"\r\n\r\ncomma\r\n--9d85bfe775eb4da6a4b39643d9b62963\r\nContent-Disposition: form-data; name="name"\r\n\r\nSearches\r\n--9d85bfe775eb4da6a4b39643d9b62963\r\nContent-Disposition: form-data; name="delimeter"\r\n\r\ndouble\r\n--9d85bfe775eb4da6a4b39643d9b62963\r\nContent-Disposition: form-data; name="file"; filename="file"\r\n\r\ntest,test,test\r\n--9d85bfe775eb4da6a4b39643d9b62963--\r\n'
reply: 'HTTP/1.1 400 BAD REQUEST\r\n'
header: Allow: GET, POST, DELETE, HEAD, OPTIONS
header: Content-Type: application/json
header: Date: Mon, 14 Sep 2015 16:20:25 GMT
header: Server: nginx
header: Vary: Accept
header: X-Frame-Options: SAMEORIGIN
header: Content-Length: 115
header: Connection: keep-alive

Performing the same request using the curl command suggested on the docs page works successfully.

**Comment by robingustafsson** [comment]
@timwintle Thanks for reporting. This seems like a documentation bug in the README. The "delim**e**ter" parameter should be "delim**i**ter". I'll update the README and also the SDK to print a better error message (the current one is just "Validation failed"), whereas the API responds with a little bit more information:
```json
{
    "message": "Validation failed",
    "errors": {
        "delimiter": "delimiter should be \"double\", \"single\" or \"none\""
    }
}
```

**Comment by robingustafsson** [comment]
I've now updated the README and the API error response handling. A new version of the SDK has been uploaded to PyPI: [https://pypi.python.org/pypi/loadimpact/1.1.4](https://pypi.python.org/pypi/loadimpact/1.1.4).

Again, thanks for reporting.
